import {readFile} from 'node:fs/promises';
import assert from 'node:assert/strict';
import {createModel} from '../src/core/model.js';
import {installIndexEngineBridge} from '../src/ui/indexBridge.js';
import {createProductBook,extractProductModel} from '../src/ui/indexNativePersistence.js';
import {createWebMcpTools} from '../src/ui/webmcp/tools.js';
import {workflowStatus} from '../src/ui/webmcp/workflowStatus.js';
import {boundedResultSlice} from '../src/core/boundedResultSlice.js';
import {buildImagePdf,createBrowserReviewPdfExporter} from '../src/report/phase22/browserReviewPdf.js';
import {createP22Report} from './fixtures/p22-report.js';
import {createBrowserMemoryDiagnostics} from '../src/compute/telemetry/browserMemory.js';
import {createResourceBudget,retainedBytes} from '../src/core/resourceBudget.js';
const good=x=>{assert.equal(x.ok,true,JSON.stringify(x));return x;};
const m=createModel();m.meta={projectId:'P22-SYNTHETIC'};
m.nodes=[{id:'A',x:0,y:0,z:0,support:'fixed'},{id:'B',x:0,y:0,z:3}];m.members=[{id:'AB',type:'frame',n1:'A',n2:'B',matId:'steel',secId:'h300'}];m.loads=[{id:'F',type:'nodal',node:'B',P:1,dir:'+x',case:'D'}];m.loadCases=[{id:'D',type:'dead'}];m.loadCombinations=[{id:'S',name:'synthetic',type:'service',factors:{D:1}}];m.analysisCases=[{id:'STATIC',kind:'static',settings:{comboId:'S',pDeltaMethod:'off'}}];
Object.assign(m,extractProductModel(createProductBook(m)));
const saved=new Map(),storage={put:async(k,v)=>saved.set(k,structuredClone(v)),get:async k=>structuredClone(saved.get(k))};
const target={model:()=>m,location:{search:''},SStructuresCheckpointStorage:storage},bridge=installIndexEngineBridge(target),tools=createWebMcpTools({agent:target.SStructuresAgent,bridge}),call=(name,args={})=>tools.find(t=>t.name===name).execute(args);
const plan=good(await call('plan_elastic_workflow',{inputHash:bridge.getWorkflowInputIdentity().inputHash,caseIds:['STATIC']}));
const started=good(await call('start_elastic_workflow',{handle:plan.handle,requestId:'synthetic'}));let w;
for(let i=0;i<50;i++){w=await call('get_elastic_workflow',{handle:started.handle});if(w.status!=='running')break;await new Promise(r=>setTimeout(r,5));}
assert.equal(w.status,'completed');const step=w.result.steps[0];
assert.equal((await call('get_analysis_status',{jobId:step.jobId})).status.status,'completed');
assert.ok((await call('get_result_slice',{jobId:step.jobId})).slice.data);
assert.match(workflowStatus(bridge),/현재 입력 해석 1건/);
const alias=await call('open_analysis_result',{analysisRunId:step.analysisRunId});assert.ok((await call('get_result_slice',{jobId:alias.jobId})).slice.data);
await assert.rejects(call('cancel_analysis',{jobId:alias.jobId}),{code:'READ_ONLY_RESULT'});
await assert.rejects(call('get_result_slice',{jobId:'foreign-session'}),{code:'JOB_NOT_FOUND'});
await bridge.saveWorkflowCheckpoint({projectId:'P22-SYNTHETIC'});
const freshModel=createModel(),fresh={model:()=>freshModel,location:{search:''},SStructuresCheckpointStorage:storage},restored=installIndexEngineBridge(fresh);
await restored.restoreWorkflowCheckpoint({projectId:'P22-SYNTHETIC'});
const freshTools=createWebMcpTools({agent:fresh.SStructuresAgent,bridge:restored}),freshCall=(name,args)=>freshTools.find(t=>t.name===name).execute(args);
await assert.rejects(freshCall('get_result_slice',{jobId:alias.jobId}),{code:'JOB_NOT_FOUND'});
const reopened=await freshCall('open_analysis_result',{analysisRunId:step.analysisRunId});assert.equal((await freshCall('get_result_slice',{jobId:reopened.jobId})).stale,false,JSON.stringify({record:restored.getWorkflowAnalysisMetadata(step.analysisRunId).identity,current:restored.getWorkflowInputIdentity({caseId:'STATIC'})}));
freshModel.nodes[1].x+=1;assert.equal((await freshCall('get_result_slice',{jobId:reopened.jobId})).stale,true);assert.match(workflowStatus(restored),/입력 변경됨/);
const source={summary:{value:1},get payload(){throw Error('Unselected payload must not be read');}};
const slice=boundedResultSlice(source);slice.data.value=9;assert.equal(source.summary.value,1);
assert.throws(()=>boundedResultSlice({payload:{x:'x'.repeat(64000)}},{path:'payload.x'}),{code:'RESULT_TOO_LARGE'});
assert.throws(()=>boundedResultSlice(source,{path:'payload.__proto__'}),{code:'INVALID_PATH'});
const same={x:'abc'};assert.ok(retainedBytes({a:same,b:same})<retainedBytes({a:same,b:{...same}}));
const pdf=buildImagePdf([{width:1,height:1,bytes:new Uint8Array([255,216,255,217])}]);const text=new TextDecoder().decode(pdf);assert.match(text,/^%PDF-1.4/);assert.match(text,/\/Count 1/);const xref=Number(text.match(/startxref\n(\d+)/)[1]);assert.equal(text.slice(xref,xref+4),'xref');
assert.throws(()=>buildImagePdf([]),{code:'PDF_PAGE_LIMIT'});assert.throws(()=>buildImagePdf([{width:1,height:1,bytes:new Uint8Array([255,216])}],{maxBytes:10}),{code:'PDF_SIZE_LIMIT'});
const probe=createBrowserMemoryDiagnostics({crossOriginIsolated:true,performance:{measureUserAgentSpecificMemory:async()=>({bytes:123})}},()=>({totalBytes:4}));
assert.equal((await probe()).aggregate.status,'not-requested');assert.equal((await probe({includeAggregate:true})).aggregate.bytes,123);
assert.equal((await bridge.getRuntimeResources({includeAggregate:true})).aggregate.bytes,null);
const pdfBudget=createResourceBudget(),mockContext={fillRect(){},fillText(){},measureText:t=>({width:t.length*10})};
const exporter=createBrowserReviewPdfExporter({document:{createElement:()=>({getContext:()=>mockContext})},Blob,URL:{createObjectURL(){}},atob,setTimeout,clearTimeout},pdfBudget,{loadFont:async()=>new Uint8Array(await readFile(new URL('../assets/fonts/phase24/SStructuresSans.ttf',import.meta.url)))});
let checks=0;await assert.rejects(exporter.export(createP22Report(),{download:false,assertCurrent:()=>{if(++checks>1)throw Object.assign(new Error('STALE_INPUT'),{code:'STALE_INPUT'});}}),{code:'STALE_INPUT'});assert.equal(pdfBudget.snapshot().totalBytes,0);
const altered=createP22Report();altered.snapshot.designReview.summary.status='OK';await assert.rejects(exporter.export(altered),{code:'PDF_SNAPSHOT_HASH_MISMATCH'});exporter.dispose();assert.equal(exporter.supported(),false);
tools.dispose();freshTools.dispose();await bridge.disposeRuntime();await restored.disposeRuntime();assert.equal(bridge.getResourceState().totalBytes,0);assert.equal(restored.getResourceState().totalBytes,0);
console.log('PASS P22 synthetic workflow/session/restore/stale/slice isolation/memory/PDF structure');

