import { MODELING_ACTIONS } from './indexAgentActions.js';
import { NATIVE_ADVANCED_ACTIONS } from './indexNativeAdvancedAnalysis.js';
import { NATIVE_AGENT_CONTROL_ACTIONS } from './indexNativeAgentControls.js';
import { NATIVE_MODELER_ACTIONS } from './indexNativeModeler.js';
import { MATERIAL_LIBRARY_ACTIONS } from '../materials/libraryEdit.js';
import { P11_REPORT_EXPORT_ACTIONS } from './indexReportExportWorkflow.js';

export function availableAgentActions() {
  return [
    'runAnalysis',
    'setModel',
    'setAnalysisSetting',
    'setResultTab',
    'setPDeltaStep',
    'setViewerSlice',
    'setResultsPanelOpen',
    'setOverlayOption',
    'setOverlayMode',
    'setOverlayPDeltaStep',
    'focusEntity',
    'setPushoverOption',
    'setPushoverPanelOpen',
    'runPushover',
    'addAnalysisCase',
    'updateAnalysisCase',
    'deleteAnalysisCase',
    'listAnalysisCases',
    'runAnalysisCase',
    'runAnalysisCases',
    'runAllAnalysisCases',
    'getAnalysisCaseResult',
    'getAnalysisCapabilities',
    'validateAnalysisRun',
    'planAnalysisRun',
    'startAnalysisRun',
    'getAnalysisRunStatus',
    'listAnalysisRuns',
    'getAnalysisRunResult',
    'getAnalysisResultSlice',
    'cancelAnalysisRun',
    'retryAnalysisRun',
    'getAnalysisRunReport',
    'exportAnalysisTelemetry',
    'validateNonlinearCase',
    'createProductionNonlinearCase',
    'previewNonlinearAssignments',
    'applyNonlinearAssignments',
    'startNonlinearRun',
    'pauseNonlinearRun',
    'cancelNonlinearRun',
    'resumeNonlinearRun',
    'retryNonlinearRun',
    'getNonlinearRunStatus',
    'listNonlinearRuns',
    'getNonlinearRunGraph',
    'getNonlinearResult',
    'getNonlinearResultSlice',
    'explainNonlinearFailure',
    'exportNonlinearHistory',
    'getNonlinearReport',
    'applyKdsLoadCombinations',
    'applyKdsRuleBasedLoadCombinations',
    'applyDesignBasisLoads',
    'setDesignBasisInput',
    ...MATERIAL_LIBRARY_ACTIONS,
    'openNativeDetailedReport',
    'openNativeCalculationPackage',
    ...P11_REPORT_EXPORT_ACTIONS,
    'setNativeMode',
    'setNativePDeltaEnabled',
    'setNativePDeltaStep',
    'setNativeResultScale',
    'showNativeMemberResult',
    ...NATIVE_MODELER_ACTIONS,
    'loadNativeExample',
    'exportNativeBook',
    'importNativeBook',
    'saveNativeAutosave',
    'restoreNativeAutosave',
    ...NATIVE_AGENT_CONTROL_ACTIONS,
    ...NATIVE_ADVANCED_ACTIONS,
    'runNativeProductAudit',
    ...MODELING_ACTIONS,
  ];
}
