export const workspaceUxStyles=`
:root{--ss-ux-panel-z:19010;--ss-ux-menu-z:19100}
#ssAgentConnection .ss-work-body p{margin:10px 0;line-height:1.55}#ssAgentConnection ol{padding-left:24px;line-height:1.7}#ssAgentConnection summary{cursor:pointer}
.ss-work-window{position:fixed;z-index:var(--ss-ux-panel-z);display:flex;flex-direction:column;overflow:hidden;background:var(--paper,#fbfcfe);color:#172338;border:1px solid #b6c3d6;border-radius:10px;box-shadow:0 12px 40px #00274433;font:14px system-ui;box-sizing:border-box}
.ss-work-window[hidden]{display:none!important}.ss-work-header{display:flex;align-items:center;gap:8px;background:#eef4fa;padding:10px 16px;border-bottom:1px solid #c9d8e6;flex-shrink:0}.ss-work-header h2{font-size:17px!important;margin:0!important;flex:1;white-space:nowrap}.ss-work-hint{font-size:11px;color:#536a80}.ss-work-body{overflow:auto;padding:16px;min-height:0;flex:1;overscroll-behavior:contain}.ss-work-footer{display:flex;align-items:center;flex-wrap:wrap;gap:4px;padding:6px 16px;background:#eef4fa;flex-shrink:0}.ss-work-footer:empty{display:none}
.ss-work-window button,.ss-ux-shortcuts button,#ssNativeRibbon>div>button{font:inherit;min-height:32px;padding:6px 10px;border:1px solid #bacfe0;border-radius:6px;background:#edf3fa;color:#00467f;cursor:pointer}
.ss-work-window button:disabled{opacity:.45;cursor:not-allowed}.ss-work-window input,.ss-work-window select,.ss-work-window textarea{font:inherit;min-height:32px;box-sizing:border-box;max-width:100%;border:1px solid #b6c3d6;border-radius:5px;padding:6px 8px;background:white;color:#172338}.ss-work-window input[type=checkbox]{min-height:auto}
.ss-work-window button:focus-visible,.ss-work-window input:focus-visible,.ss-work-window select:focus-visible,summary:focus-visible{outline:2px solid #0a5ca8;outline-offset:2px}
.ss-ux-nav{display:flex;gap:5px;flex-wrap:wrap;padding:8px 16px;background:white;border-bottom:1px solid #c9d8e6;flex-shrink:0}.ss-ux-nav button{margin:0!important}.ss-ux-nav button[aria-current=true]{background:#00467f!important;color:white!important}
.ss-ux-task{margin:14px 0;border:1px solid #c9d8e6;border-radius:6px;padding:10px;background:white}.ss-ux-task>summary{cursor:pointer;color:#00467f;font-weight:600;padding:6px}.ss-ux-task[open]>summary{border-bottom:1px solid #dbe5ee;margin-bottom:10px}.ss-ux-advanced{margin:10px 0;padding:10px;border:1px solid #c9d8e6;border-radius:6px}.ss-ux-advanced>summary{cursor:pointer;font-weight:600;color:#00467f}.ss-ux-shortcuts{display:flex;gap:6px;align-items:center;flex-wrap:wrap;font-size:12px}.ss-ux-shortcuts select{max-width:160px;padding:6px;border:1px solid #b6c3d6;border-radius:5px}.ss-ux-shortcuts button{white-space:nowrap}
#subbar{position:relative;z-index:10000}#topbar{position:relative;z-index:10001;gap:8px;overflow-x:auto;flex-wrap:nowrap}#topbar>*{flex-shrink:0}#topbar button,#topbar .ss-ribbon-group{white-space:nowrap}#topbar [data-ss-ribbon-items]{flex-wrap:nowrap}#topbar .ss-ribbon-common{flex-shrink:0}
#ssDesignReview label{display:inline-flex!important;flex-direction:column;vertical-align:top;gap:4px;min-width:190px;max-width:100%;font-size:13px;margin:6px!important}#ssDesignReview h4{margin:14px 0 8px;color:#00467f}#ssDesignReview p{line-height:1.6}#ssDesignReview textarea{width:100%!important}#ssDesignReview input:not([type=checkbox]){width:220px}#ssDesignReview pre{overflow-wrap:anywhere}
#ssDesignReview .ss-ux-result-hint{background:#eef4fa;padding:8px;border-left:3px solid #00467f}
#ssDesignInputs .ss-ux-fieldset{grid-column:1/-1;border:1px solid #c9d8e6;border-radius:6px;display:grid;grid-template-columns:repeat(auto-fit,minmax(210px,1fr));gap:12px;padding:12px}#ssDesignInputs .ss-ux-fieldset legend{color:#00467f;font-weight:600}
#menuDrop{position:fixed!important;z-index:var(--ss-ux-menu-z)!important;max-height:calc(100vh - 16px);overflow:auto;box-sizing:border-box}#menuDrop .ss-ux-menu-label{font-size:11px;color:#58748d;padding:8px 12px 4px;border-top:1px solid #dbe5ee;margin-top:4px}
.ss-ux-ribbon-more{font:12px system-ui;position:relative}.ss-ux-ribbon-more>summary{padding:8px 12px;border:1px solid #bad0e0;border-radius:6px;color:#00467f;cursor:pointer;white-space:nowrap}.ss-ux-ribbon-more[open]>.ss-ux-more-body{display:flex;flex-wrap:wrap;gap:8px;padding:10px;background:#f6f9fc}.ss-ux-ribbon-more:not([open])>.ss-ux-more-body{display:none}
@media(max-width:1100px){.ss-work-hint{display:none}.ss-work-header{padding:6px 10px}.ss-work-header h2{font-size:15px!important}.ss-work-body{padding:12px}#ssNativeRibbon{font-size:12px}.ss-ux-shortcuts{gap:4px}}
@media(pointer:coarse){.ss-work-window button,.ss-ux-shortcuts button,.ss-work-window input,.ss-work-window select{min-height:44px}}
`;
