// Bounded, deterministic ZIP32 store archive. File names are generated by the
// report owner; no paths or arbitrary archive metadata are accepted.
const crcTable=Uint32Array.from({length:256},(_,n)=>{for(let k=0;k<8;k++)n=n&1?0xedb88320^(n>>>1):n>>>1;return n>>>0;});
export function buildStoredZip(files,{maxBytes=32*1024*1024}={}){
 const fail=()=>{throw Object.assign(new Error('DRAWING_BUNDLE_SIZE_OR_ENTRY_INVALID'),{code:'DRAWING_BUNDLE_SIZE_OR_ENTRY_INVALID'});};
 if(!Array.isArray(files)||!files.length||files.length>11||!Number.isSafeInteger(maxBytes)||maxBytes<22||maxBytes>32*1024*1024)fail();
 const names=new Set();let total=22;
 const entries=files.map(f=>{
  if(!/^[A-Za-z0-9_-]+\.(pdf|json)$/.test(f.name)||f.name.length>100||names.has(f.name)||!(f.bytes instanceof Uint8Array))fail();
  names.add(f.name);const name=new TextEncoder().encode(f.name);total+=76+2*name.length+f.bytes.length;if(total>maxBytes)fail();
  let crc=0xffffffff;for(const b of f.bytes)crc=crcTable[(crc^b)&255]^(crc>>>8);
  return {...f,name,crc:(crc^0xffffffff)>>>0};
 });
 const out=new Uint8Array(total),view=new DataView(out.buffer);let at=0;
 const u16=(p,n)=>view.setUint16(p,n,true),u32=(p,n)=>view.setUint32(p,n,true);
 for(const e of entries){
  e.offset=at;u32(at,0x04034b50);u16(at+4,20);u16(at+12,33); // 1980-01-01
  u32(at+14,e.crc);u32(at+18,e.bytes.length);u32(at+22,e.bytes.length);u16(at+26,e.name.length);
  out.set(e.name,at+30);out.set(e.bytes,at+30+e.name.length);at+=30+e.name.length+e.bytes.length;
 }
 const central=at;
 for(const e of entries){
  u32(at,0x02014b50);u16(at+4,20);u16(at+6,20);u16(at+14,33);u32(at+16,e.crc);
  u32(at+20,e.bytes.length);u32(at+24,e.bytes.length);u16(at+28,e.name.length);u32(at+42,e.offset);
  out.set(e.name,at+46);at+=46+e.name.length;
 }
 u32(at,0x06054b50);u16(at+8,entries.length);u16(at+10,entries.length);u32(at+12,at-central);u32(at+16,central);
 return out;
}
