"""Build credential-free runtime indexes from already captured official envelopes."""
import json,re,hashlib
from pathlib import Path
root=Path(__file__).resolve().parents[1]
folders=[root/'verification/evidence/phase24/kcsc',root/'verification/evidence/phase25/kcsc/official-20260911']
sources=[];clauses=[];tokens=[]
for folder in folders:
    manifest=json.loads((folder/'retrieval-manifest.json').read_text(encoding='utf-8'))
    for record in manifest['records']:
        data=(folder/record['file']).read_bytes();digest=hashlib.sha256(data).hexdigest()
        if digest!=record['sha256']:raise ValueError('Source hash mismatch')
        doc=json.loads(data)[0];code=doc['code'];edition=str(doc['version'])
        if not re.fullmatch(r'\d{6}',code) or not re.fullmatch(r'\d{4}',edition):raise ValueError('Document identity invalid')
        sources.append({'id':code,'code':f'KDS {code[:2]} {code[2:4]} {code[4:]}','name':doc['name'],'edition':edition,'updateDate':doc['updateDate'],'url':record['source'],'retrievedAt':record['retrievedAt'],'sha256':digest,'verification':'official-source-captured-independent-review-pending'})
        headings=set();equations=set();appendix_headings=set();appendix_equations=set();appendix=False
        for row in doc['list']:
            title=re.sub('<[^>]+>',' ',row.get('title','')).strip()
            body=re.sub('<[^>]+>',' ',row.get('contents','')).strip()
            if re.match(r'부록',title) or re.match(r'부록',body):appendix=True
            match=re.match(r'(\d+(?:\.\d+)+)(?![\d.])',title)
            if match:(appendix_headings if appendix else headings).add(match[1])
            (appendix_equations if appendix else equations).update(re.findall(r'(?<!\d)(\d+(?:\.\d+)+-\d+)(?!\d)',row.get('contents','')))
        clauses.append({'id':code,'edition':edition,'sha256':digest,'clauses':sorted(headings),'appendixClauses':sorted(appendix_headings),'scope':'separate main-body and appendix heading namespaces'})
        tokens.append({'id':code,'sha256':digest,'tokens':sorted(equations),'appendixTokens':sorted(appendix_equations)})
def emit(filename,name,rows):
    (root/'src/metadata'/filename).write_text('// Generated by tools/build-p25-source-index.py; existence is not implementation qualification.\nexport const '+name+'='+json.dumps(rows,ensure_ascii=False,separators=(',',':'))+';\n',encoding='utf-8')
emit('kdsClauseIndex.js','KDS_CLAUSE_INDEX',clauses)
emit('kdsReferenceTokens.js','KDS_REFERENCE_TOKENS',tokens)
emit('kcscRuleSources.js','KCSC_RULE_SOURCES',sources)
with (root/'src/metadata/kcscRuleSources.js').open('a',encoding='utf-8') as out:out.write('export function getKcscRuleSources(ids){return KCSC_RULE_SOURCES.filter(x=>ids.includes(x.id)).map(x=>({...x}));}\n')
print(json.dumps({'documents':len(sources),'credentialStored':False}))
